name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  # ===========================================
  # Build Electron Apps for All Platforms
  # ===========================================
  build-electron:
    name: Build Electron - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS builds (both Intel and Apple Silicon)
          - os: macos-latest
            platform: mac
            arch: x64,arm64

          # Windows builds (Intel and ARM)
          - os: windows-latest
            platform: win
            arch: x64,arm64

          # Linux builds (Intel and ARM)
          - os: ubuntu-latest
            platform: linux
            arch: x64,arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build:${{ matrix.platform }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist-electron/*.exe
            dist-electron/*.dmg
            dist-electron/*.zip
            dist-electron/*.AppImage
            dist-electron/*.deb
            dist-electron/*.rpm
          retention-days: 7

  # ===========================================
  # Build and Push Docker Images
  # ===========================================
  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_short=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/devorbit-frontend:latest
            ghcr.io/${{ github.repository_owner }}/devorbit-frontend:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/devorbit-frontend:${{ steps.version.outputs.version_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/devorbit-api:latest
            ghcr.io/${{ github.repository_owner }}/devorbit-api:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/devorbit-api:${{ steps.version.outputs.version_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push All-in-One image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/devorbit:latest
            ghcr.io/${{ github.repository_owner }}/devorbit:${{ steps.version.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/devorbit:${{ steps.version.outputs.version_short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ===========================================
  # Create GitHub Release
  # ===========================================
  create-release:
    name: Create GitHub Release
    needs: [build-electron, build-docker]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display artifact structure
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: DevOrbit Dashboard ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## DevOrbit Dashboard ${{ steps.version.outputs.version }}

            ### Desktop Applications (Electron)

            Download the appropriate installer for your operating system:

            **Windows:**
            - `DevOrbit-Dashboard-Setup-*.exe` - Installer (x64)
            - `DevOrbit-Dashboard-*-arm64.exe` - Installer (ARM64)
            - `DevOrbit-Dashboard-*.exe` - Portable version (x64)

            **macOS:**
            - `DevOrbit-Dashboard-*.dmg` - DMG installer (Universal: Intel & Apple Silicon)
            - `DevOrbit-Dashboard-*-mac.zip` - ZIP archive (Universal)

            **Linux:**
            - `DevOrbit-Dashboard-*.AppImage` - AppImage (x64 & ARM64)
            - `DevOrbit-Dashboard-*.deb` - Debian/Ubuntu package (x64 & ARM64)
            - `DevOrbit-Dashboard-*.rpm` - Fedora/RHEL package (x64 & ARM64)

            ### Docker Images

            Docker images are available on GitHub Container Registry:

            ```bash
            # Pull the all-in-one image
            docker pull ghcr.io/${{ github.repository_owner }}/devorbit:${{ steps.version.outputs.version }}

            # Or pull specific components
            docker pull ghcr.io/${{ github.repository_owner }}/devorbit-frontend:${{ steps.version.outputs.version }}
            docker pull ghcr.io/${{ github.repository_owner }}/devorbit-api:${{ steps.version.outputs.version }}
            ```

            **Using Docker Compose:**

            ```bash
            # Download the docker-compose.yml file from this repository
            wget https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml

            # Start the application
            docker compose up -d
            ```

            ### What's Included

            - AI-powered project analysis with Gemini
            - Multi-project monitoring and management
            - Integrated terminal emulator
            - Docker container support
            - VS Code integration (code-server)
            - PostgreSQL and Redis for data persistence

            ### Installation Instructions

            #### Desktop App
            1. Download the appropriate installer for your platform
            2. Run the installer
            3. Launch DevOrbit Dashboard
            4. Configure your project directories in settings

            #### Docker
            1. Ensure Docker and Docker Compose are installed
            2. Download the `docker-compose.yml` file
            3. Create a `.env` file with required variables (see `.env.example`)
            4. Run `docker compose up -d`
            5. Access the dashboard at `http://localhost:3000`

            ### Documentation

            For more information, see the [README](https://github.com/${{ github.repository }}/blob/main/README.md)
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.zip
            artifacts/**/*.AppImage
            artifacts/**/*.deb
            artifacts/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
